### ISSUE TITLE
Review Submission

### ISSUE THREAD

**Issue by not-xygen** [desssti06/project-web-dev-1#1]
### Halo Desti,

Ada beberapa kesalahan nih dalam struktur kodenya

1.Kodemu seperti ini:
![image](https://github.com/desssti06/project-web-dev-1/assets/73971391/9f3d2ce3-06df-42af-86ef-f9fc9c8e61e0)
seharusnya struktrunya seperti:
```html
<header>...</header>
<main>
 <div id="content">
  <section>....</section>
  <section>....</section>
  .....
 </div>
 <aside>....</div>
</main>
<footer>...</footer>
```
tapi karena kamu ada elemen penambah di website kamu. Kamu bisa memindahkan elemen `nav` ke `header`,  kamu bisa memindahkan `div id="banner"` kedalam `main`. Dikarenakan ada banner didalam website, aku saranin struktur htmlmu sebagai berikut
```html
<main>
 <div id="banner">...</div>
 <div id="content-container">
  <div id="content">
   <section>....</section>
   <section>....</section>
    .....
  </div>
  <aside>....</div>
 </div>
</main>
```

itu aja dari aku, bisa direvisi dan di upload ulang di repository ini ya. Thanks dan jangan lupa komen dibawah kalau sudah

**Comment by desssti06** [comment]
saya sudah revisi ya kak

**Comment by not-xygen** [comment]
### Halo desti,

Dari struktur yang sekarang udah oke nih, tapi satu kesalahan ni
![image](https://github.com/desssti06/project-web-dev-1/assets/73971391/87785b99-44fb-4c93-8cfe-6e75426ba593)
kamu gamasukin konten artikelnya ke elemen `article`. Bisa dimasukin ya, terus untuk aside gapapa sementara dibawah gitu karena nanti kamu akan memperbaikinya pada belajar CSS. tetapi sekarang udah oke jadi dibaikin ya. Submission ini kuapprove dan goodluck untuk CSS nanti.
